{% set name = "aws-sdk-cpp" %}
{% set version = "1.11.212" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 891b0b7107c942e6413e8b46ea41c5e9b856d6b984dfcce275d1688ab55d21ef

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-sdk-cpp", max_pin="x.x.x") }}
  missing_dso_whitelist:
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - cmake >=3.2
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja-base
    - make  # [unix]

  host:
    - aws-c-common 0.8.5
    - aws-c-event-stream 0.2.15
    - aws-crt-cpp 0.18.16
    - aws-checksums 0.1.13
    - libcurl 8.9.1
    - openssl {{ openssl }}  # [linux]
    - zlib

test:
  files:
    - test.cpp
    - CMakeLists.txt
  requires:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja-base
    - make  # [unix]
  # test commands in run_test.{sh,bat} files

about:
  home: https://github.com/aws/aws-sdk-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ library that makes it easy to integrate C++ applications with AWS services
  description: |
    The AWS SDK for C++ provides a modern C++ (version C++ 11 or later) interface for Amazon Web Services (AWS).
    It is meant to be performant and fully functioning with low- and high-level SDKs,
    while minimizing dependencies and providing platform portability (Windows, OSX, Linux, and mobile).
  doc_url: https://docs.aws.amazon.com/sdk-for-cpp
  dev_url: https://github.com/aws/aws-sdk-cpp

extra:
  recipe-maintainers:
    - jakebolewski
    - pitrou
    - ihnorton
    - xhochy
