{% set name = "aws-sdk-cpp" %}
{% set version = "1.4.57" %}
{% set sha256 = "81f4e86135db764b1f556d046fb94a22f0f9da415fb58179d0ccb4ff119af2fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/aws/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
 number: 0
 skip: True  # [win]

requirements:
  build:
    - toolchain
    - cmake >=3.2
    - curl >=7.44.0,<8
    - openssl 1.0.*
    - zlib 1.2.11
  run:
    - curl >=7.44.0,<8
    - openssl 1.0.*
    - zlib 1.2.11

test:
  files:
    - test.cpp
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/aws/aws-sdk-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'C++ library that makes it easy to integrate C++ applications with AWS services'

  description: |
    The AWS SDK for C++ provides a modern C++ (version C++ 11 or later) interface for Amazon Web Services (AWS).
    It is meant to be performant and fully functioning with low- and high-level SDKs, 
    while minimizing dependencies and providing platform portability (Windows, OSX, Linux, and mobile).
  doc_url: https://aws.amazon.com/documentation/sdk-for-cpp/
  dev_url: https://github.com/aws/aws-sdk-cpp

extra:
  recipe-maintainers:
    - jakebolewski
