schema_version: 1

context:
  version: 1.11.489

package:
  name: aws-sdk-cpp
  version: ${{ version }}

source:
  url: https://github.com/aws/aws-sdk-cpp/archive/${{ version }}.tar.gz
  sha256: 89ce525c735243a043c5a31eee5dc082fc976b9b5a4b0b66813eed48c97abbfa

build:
  number: 1

requirements:
  build:
    - cmake >=3.2
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - ninja
    - if: unix
      then: make
  host:
    - aws-c-common
    - aws-c-event-stream
    - aws-checksums
    - aws-crt-cpp
    - if: not win
      then: libcurl
    - if: not win
      then: openssl
    - zlib
  run_exports:
    - ${{ pin_subpackage("aws-sdk-cpp", upper_bound="x.x.x") }}

tests:
  - files:
      recipe:
        - test.cpp
        - CMakeLists.txt
    requirements:
      run:
        - cmake
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ninja
        - if: unix
          then: make
    script: commands

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C++ library that makes it easy to integrate C++ applications with AWS services
  description: |
    The AWS SDK for C++ provides a modern C++ (version C++ 11 or later) interface for Amazon Web Services (AWS).
    It is meant to be performant and fully functioning with low- and high-level SDKs,
    while minimizing dependencies and providing platform portability (Windows, OSX, Linux, and mobile).
  homepage: https://github.com/aws/aws-sdk-cpp
  repository: https://github.com/aws/aws-sdk-cpp
  documentation: https://aws.amazon.com/documentation/sdk-for-cpp/

extra:
  recipe-maintainers:
    - pitrou
    - ihnorton
    - xhochy
